# Site settings
title: fairundreineoele
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/fairundreineoele" # the subpath of your site, e.g. /blog/
url: "https://spegioloni.github.io/fairundreineoele" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
